/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkoutRouteImport } from './routes/_authenticated/workout'
import { Route as AuthenticatedWellnessRouteImport } from './routes/_authenticated/wellness'
import { Route as AuthenticatedWaqfRouteImport } from './routes/_authenticated/waqf'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQuranRouteImport } from './routes/_authenticated/quran'
import { Route as AuthenticatedQiblaRouteImport } from './routes/_authenticated/qibla'
import { Route as AuthenticatedPrayerRouteImport } from './routes/_authenticated/prayer'
import { Route as AuthenticatedMealRouteImport } from './routes/_authenticated/meal'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedGamificationRouteImport } from './routes/_authenticated/gamification'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFemaleRouteImport } from './routes/_authenticated/female'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedChildrenRouteImport } from './routes/_authenticated/children'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedQuranIndexRouteImport } from './routes/_authenticated/quran/index'
import { Route as AuthenticatedHabitsIndexRouteImport } from './routes/_authenticated/habits/index'
import { Route as AuthenticatedQuranStatsRouteImport } from './routes/_authenticated/quran/stats'
import { Route as AuthenticatedQuranSearchRouteImport } from './routes/_authenticated/quran/search'
import { Route as AuthenticatedQuranPracticeRouteImport } from './routes/_authenticated/quran/practice'
import { Route as AuthenticatedQuranHifzRouteImport } from './routes/_authenticated/quran/hifz'
import { Route as AuthenticatedQuranHadithRouteImport } from './routes/_authenticated/quran/hadith'
import { Route as AuthenticatedQuranDuasRouteImport } from './routes/_authenticated/quran/duas'
import { Route as AuthenticatedQuranBookmarksRouteImport } from './routes/_authenticated/quran/bookmarks'
import { Route as AuthenticatedHabitsLibraryRouteImport } from './routes/_authenticated/habits/library'
import { Route as AuthenticatedHabitsDhikrRouteImport } from './routes/_authenticated/habits/dhikr'
import { Route as AuthenticatedHabitsAnalyticsRouteImport } from './routes/_authenticated/habits/analytics'
import { Route as AuthenticatedHabitsIdRouteImport } from './routes/_authenticated/habits/$id'
import { Route as AuthenticatedQuranSurahIdRouteImport } from './routes/_authenticated/quran/surah.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutRoute = AuthenticatedWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWellnessRoute = AuthenticatedWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWaqfRoute = AuthenticatedWaqfRouteImport.update({
  id: '/waqf',
  path: '/waqf',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuranRoute = AuthenticatedQuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQiblaRoute = AuthenticatedQiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrayerRoute = AuthenticatedPrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMealRoute = AuthenticatedMealRouteImport.update({
  id: '/meal',
  path: '/meal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamificationRoute =
  AuthenticatedGamificationRouteImport.update({
    id: '/gamification',
    path: '/gamification',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFemaleRoute = AuthenticatedFemaleRouteImport.update({
  id: '/female',
  path: '/female',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChildrenRoute = AuthenticatedChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuranIndexRoute = AuthenticatedQuranIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedQuranRoute,
} as any)
const AuthenticatedHabitsIndexRoute =
  AuthenticatedHabitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHabitsRoute,
  } as any)
const AuthenticatedQuranStatsRoute = AuthenticatedQuranStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedQuranRoute,
} as any)
const AuthenticatedQuranSearchRoute =
  AuthenticatedQuranSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedQuranRoute,
  } as any)
const AuthenticatedQuranPracticeRoute =
  AuthenticatedQuranPracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => AuthenticatedQuranRoute,
  } as any)
const AuthenticatedQuranHifzRoute = AuthenticatedQuranHifzRouteImport.update({
  id: '/hifz',
  path: '/hifz',
  getParentRoute: () => AuthenticatedQuranRoute,
} as any)
const AuthenticatedQuranHadithRoute =
  AuthenticatedQuranHadithRouteImport.update({
    id: '/hadith',
    path: '/hadith',
    getParentRoute: () => AuthenticatedQuranRoute,
  } as any)
const AuthenticatedQuranDuasRoute = AuthenticatedQuranDuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => AuthenticatedQuranRoute,
} as any)
const AuthenticatedQuranBookmarksRoute =
  AuthenticatedQuranBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => AuthenticatedQuranRoute,
  } as any)
const AuthenticatedHabitsLibraryRoute =
  AuthenticatedHabitsLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedHabitsRoute,
  } as any)
const AuthenticatedHabitsDhikrRoute =
  AuthenticatedHabitsDhikrRouteImport.update({
    id: '/dhikr',
    path: '/dhikr',
    getParentRoute: () => AuthenticatedHabitsRoute,
  } as any)
const AuthenticatedHabitsAnalyticsRoute =
  AuthenticatedHabitsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedHabitsRoute,
  } as any)
const AuthenticatedHabitsIdRoute = AuthenticatedHabitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedHabitsRoute,
} as any)
const AuthenticatedQuranSurahIdRoute =
  AuthenticatedQuranSurahIdRouteImport.update({
    id: '/surah/$id',
    path: '/surah/$id',
    getParentRoute: () => AuthenticatedQuranRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/children': typeof AuthenticatedChildrenRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/female': typeof AuthenticatedFemaleRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/gamification': typeof AuthenticatedGamificationRoute
  '/habits': typeof AuthenticatedHabitsRouteWithChildren
  '/journal': typeof AuthenticatedJournalRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/meal': typeof AuthenticatedMealRoute
  '/prayer': typeof AuthenticatedPrayerRoute
  '/qibla': typeof AuthenticatedQiblaRoute
  '/quran': typeof AuthenticatedQuranRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/waqf': typeof AuthenticatedWaqfRoute
  '/wellness': typeof AuthenticatedWellnessRoute
  '/workout': typeof AuthenticatedWorkoutRoute
  '/habits/$id': typeof AuthenticatedHabitsIdRoute
  '/habits/analytics': typeof AuthenticatedHabitsAnalyticsRoute
  '/habits/dhikr': typeof AuthenticatedHabitsDhikrRoute
  '/habits/library': typeof AuthenticatedHabitsLibraryRoute
  '/quran/bookmarks': typeof AuthenticatedQuranBookmarksRoute
  '/quran/duas': typeof AuthenticatedQuranDuasRoute
  '/quran/hadith': typeof AuthenticatedQuranHadithRoute
  '/quran/hifz': typeof AuthenticatedQuranHifzRoute
  '/quran/practice': typeof AuthenticatedQuranPracticeRoute
  '/quran/search': typeof AuthenticatedQuranSearchRoute
  '/quran/stats': typeof AuthenticatedQuranStatsRoute
  '/habits/': typeof AuthenticatedHabitsIndexRoute
  '/quran/': typeof AuthenticatedQuranIndexRoute
  '/quran/surah/$id': typeof AuthenticatedQuranSurahIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/children': typeof AuthenticatedChildrenRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/female': typeof AuthenticatedFemaleRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/gamification': typeof AuthenticatedGamificationRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/meal': typeof AuthenticatedMealRoute
  '/prayer': typeof AuthenticatedPrayerRoute
  '/qibla': typeof AuthenticatedQiblaRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/waqf': typeof AuthenticatedWaqfRoute
  '/wellness': typeof AuthenticatedWellnessRoute
  '/workout': typeof AuthenticatedWorkoutRoute
  '/habits/$id': typeof AuthenticatedHabitsIdRoute
  '/habits/analytics': typeof AuthenticatedHabitsAnalyticsRoute
  '/habits/dhikr': typeof AuthenticatedHabitsDhikrRoute
  '/habits/library': typeof AuthenticatedHabitsLibraryRoute
  '/quran/bookmarks': typeof AuthenticatedQuranBookmarksRoute
  '/quran/duas': typeof AuthenticatedQuranDuasRoute
  '/quran/hadith': typeof AuthenticatedQuranHadithRoute
  '/quran/hifz': typeof AuthenticatedQuranHifzRoute
  '/quran/practice': typeof AuthenticatedQuranPracticeRoute
  '/quran/search': typeof AuthenticatedQuranSearchRoute
  '/quran/stats': typeof AuthenticatedQuranStatsRoute
  '/habits': typeof AuthenticatedHabitsIndexRoute
  '/quran': typeof AuthenticatedQuranIndexRoute
  '/quran/surah/$id': typeof AuthenticatedQuranSurahIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/children': typeof AuthenticatedChildrenRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/female': typeof AuthenticatedFemaleRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/gamification': typeof AuthenticatedGamificationRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRouteWithChildren
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/meal': typeof AuthenticatedMealRoute
  '/_authenticated/prayer': typeof AuthenticatedPrayerRoute
  '/_authenticated/qibla': typeof AuthenticatedQiblaRoute
  '/_authenticated/quran': typeof AuthenticatedQuranRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/waqf': typeof AuthenticatedWaqfRoute
  '/_authenticated/wellness': typeof AuthenticatedWellnessRoute
  '/_authenticated/workout': typeof AuthenticatedWorkoutRoute
  '/_authenticated/habits/$id': typeof AuthenticatedHabitsIdRoute
  '/_authenticated/habits/analytics': typeof AuthenticatedHabitsAnalyticsRoute
  '/_authenticated/habits/dhikr': typeof AuthenticatedHabitsDhikrRoute
  '/_authenticated/habits/library': typeof AuthenticatedHabitsLibraryRoute
  '/_authenticated/quran/bookmarks': typeof AuthenticatedQuranBookmarksRoute
  '/_authenticated/quran/duas': typeof AuthenticatedQuranDuasRoute
  '/_authenticated/quran/hadith': typeof AuthenticatedQuranHadithRoute
  '/_authenticated/quran/hifz': typeof AuthenticatedQuranHifzRoute
  '/_authenticated/quran/practice': typeof AuthenticatedQuranPracticeRoute
  '/_authenticated/quran/search': typeof AuthenticatedQuranSearchRoute
  '/_authenticated/quran/stats': typeof AuthenticatedQuranStatsRoute
  '/_authenticated/habits/': typeof AuthenticatedHabitsIndexRoute
  '/_authenticated/quran/': typeof AuthenticatedQuranIndexRoute
  '/_authenticated/quran/surah/$id': typeof AuthenticatedQuranSurahIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/admin'
    | '/ai'
    | '/children'
    | '/community'
    | '/dashboard'
    | '/family'
    | '/female'
    | '/finance'
    | '/gamification'
    | '/habits'
    | '/journal'
    | '/learning'
    | '/meal'
    | '/prayer'
    | '/qibla'
    | '/quran'
    | '/settings'
    | '/subscription'
    | '/tasks'
    | '/waqf'
    | '/wellness'
    | '/workout'
    | '/habits/$id'
    | '/habits/analytics'
    | '/habits/dhikr'
    | '/habits/library'
    | '/quran/bookmarks'
    | '/quran/duas'
    | '/quran/hadith'
    | '/quran/hifz'
    | '/quran/practice'
    | '/quran/search'
    | '/quran/stats'
    | '/habits/'
    | '/quran/'
    | '/quran/surah/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/admin'
    | '/ai'
    | '/children'
    | '/community'
    | '/dashboard'
    | '/family'
    | '/female'
    | '/finance'
    | '/gamification'
    | '/journal'
    | '/learning'
    | '/meal'
    | '/prayer'
    | '/qibla'
    | '/settings'
    | '/subscription'
    | '/tasks'
    | '/waqf'
    | '/wellness'
    | '/workout'
    | '/habits/$id'
    | '/habits/analytics'
    | '/habits/dhikr'
    | '/habits/library'
    | '/quran/bookmarks'
    | '/quran/duas'
    | '/quran/hadith'
    | '/quran/hifz'
    | '/quran/practice'
    | '/quran/search'
    | '/quran/stats'
    | '/habits'
    | '/quran'
    | '/quran/surah/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/children'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/family'
    | '/_authenticated/female'
    | '/_authenticated/finance'
    | '/_authenticated/gamification'
    | '/_authenticated/habits'
    | '/_authenticated/journal'
    | '/_authenticated/learning'
    | '/_authenticated/meal'
    | '/_authenticated/prayer'
    | '/_authenticated/qibla'
    | '/_authenticated/quran'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/_authenticated/tasks'
    | '/_authenticated/waqf'
    | '/_authenticated/wellness'
    | '/_authenticated/workout'
    | '/_authenticated/habits/$id'
    | '/_authenticated/habits/analytics'
    | '/_authenticated/habits/dhikr'
    | '/_authenticated/habits/library'
    | '/_authenticated/quran/bookmarks'
    | '/_authenticated/quran/duas'
    | '/_authenticated/quran/hadith'
    | '/_authenticated/quran/hifz'
    | '/_authenticated/quran/practice'
    | '/_authenticated/quran/search'
    | '/_authenticated/quran/stats'
    | '/_authenticated/habits/'
    | '/_authenticated/quran/'
    | '/_authenticated/quran/surah/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workout': {
      id: '/_authenticated/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AuthenticatedWorkoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wellness': {
      id: '/_authenticated/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof AuthenticatedWellnessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/waqf': {
      id: '/_authenticated/waqf'
      path: '/waqf'
      fullPath: '/waqf'
      preLoaderRoute: typeof AuthenticatedWaqfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quran': {
      id: '/_authenticated/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof AuthenticatedQuranRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qibla': {
      id: '/_authenticated/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof AuthenticatedQiblaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prayer': {
      id: '/_authenticated/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof AuthenticatedPrayerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meal': {
      id: '/_authenticated/meal'
      path: '/meal'
      fullPath: '/meal'
      preLoaderRoute: typeof AuthenticatedMealRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gamification': {
      id: '/_authenticated/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof AuthenticatedGamificationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/female': {
      id: '/_authenticated/female'
      path: '/female'
      fullPath: '/female'
      preLoaderRoute: typeof AuthenticatedFemaleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/children': {
      id: '/_authenticated/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof AuthenticatedChildrenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quran/': {
      id: '/_authenticated/quran/'
      path: '/'
      fullPath: '/quran/'
      preLoaderRoute: typeof AuthenticatedQuranIndexRouteImport
      parentRoute: typeof AuthenticatedQuranRoute
    }
    '/_authenticated/habits/': {
      id: '/_authenticated/habits/'
      path: '/'
      fullPath: '/habits/'
      preLoaderRoute: typeof AuthenticatedHabitsIndexRouteImport
      parentRoute: typeof AuthenticatedHabitsRoute
    }
    '/_authenticated/quran/stats': {
      id: '/_authenticated/quran/stats'
      path: '/stats'
      fullPath: '/quran/stats'
      preLoaderRoute: typeof AuthenticatedQuranStatsRouteImport
      parentRoute: typeof AuthenticatedQuranRoute
    }
    '/_authenticated/quran/search': {
      id: '/_authenticated/quran/search'
      path: '/search'
      fullPath: '/quran/search'
      preLoaderRoute: typeof AuthenticatedQuranSearchRouteImport
      parentRoute: typeof AuthenticatedQuranRoute
    }
    '/_authenticated/quran/practice': {
      id: '/_authenticated/quran/practice'
      path: '/practice'
      fullPath: '/quran/practice'
      preLoaderRoute: typeof AuthenticatedQuranPracticeRouteImport
      parentRoute: typeof AuthenticatedQuranRoute
    }
    '/_authenticated/quran/hifz': {
      id: '/_authenticated/quran/hifz'
      path: '/hifz'
      fullPath: '/quran/hifz'
      preLoaderRoute: typeof AuthenticatedQuranHifzRouteImport
      parentRoute: typeof AuthenticatedQuranRoute
    }
    '/_authenticated/quran/hadith': {
      id: '/_authenticated/quran/hadith'
      path: '/hadith'
      fullPath: '/quran/hadith'
      preLoaderRoute: typeof AuthenticatedQuranHadithRouteImport
      parentRoute: typeof AuthenticatedQuranRoute
    }
    '/_authenticated/quran/duas': {
      id: '/_authenticated/quran/duas'
      path: '/duas'
      fullPath: '/quran/duas'
      preLoaderRoute: typeof AuthenticatedQuranDuasRouteImport
      parentRoute: typeof AuthenticatedQuranRoute
    }
    '/_authenticated/quran/bookmarks': {
      id: '/_authenticated/quran/bookmarks'
      path: '/bookmarks'
      fullPath: '/quran/bookmarks'
      preLoaderRoute: typeof AuthenticatedQuranBookmarksRouteImport
      parentRoute: typeof AuthenticatedQuranRoute
    }
    '/_authenticated/habits/library': {
      id: '/_authenticated/habits/library'
      path: '/library'
      fullPath: '/habits/library'
      preLoaderRoute: typeof AuthenticatedHabitsLibraryRouteImport
      parentRoute: typeof AuthenticatedHabitsRoute
    }
    '/_authenticated/habits/dhikr': {
      id: '/_authenticated/habits/dhikr'
      path: '/dhikr'
      fullPath: '/habits/dhikr'
      preLoaderRoute: typeof AuthenticatedHabitsDhikrRouteImport
      parentRoute: typeof AuthenticatedHabitsRoute
    }
    '/_authenticated/habits/analytics': {
      id: '/_authenticated/habits/analytics'
      path: '/analytics'
      fullPath: '/habits/analytics'
      preLoaderRoute: typeof AuthenticatedHabitsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedHabitsRoute
    }
    '/_authenticated/habits/$id': {
      id: '/_authenticated/habits/$id'
      path: '/$id'
      fullPath: '/habits/$id'
      preLoaderRoute: typeof AuthenticatedHabitsIdRouteImport
      parentRoute: typeof AuthenticatedHabitsRoute
    }
    '/_authenticated/quran/surah/$id': {
      id: '/_authenticated/quran/surah/$id'
      path: '/surah/$id'
      fullPath: '/quran/surah/$id'
      preLoaderRoute: typeof AuthenticatedQuranSurahIdRouteImport
      parentRoute: typeof AuthenticatedQuranRoute
    }
  }
}

interface AuthenticatedHabitsRouteChildren {
  AuthenticatedHabitsIdRoute: typeof AuthenticatedHabitsIdRoute
  AuthenticatedHabitsAnalyticsRoute: typeof AuthenticatedHabitsAnalyticsRoute
  AuthenticatedHabitsDhikrRoute: typeof AuthenticatedHabitsDhikrRoute
  AuthenticatedHabitsLibraryRoute: typeof AuthenticatedHabitsLibraryRoute
  AuthenticatedHabitsIndexRoute: typeof AuthenticatedHabitsIndexRoute
}

const AuthenticatedHabitsRouteChildren: AuthenticatedHabitsRouteChildren = {
  AuthenticatedHabitsIdRoute: AuthenticatedHabitsIdRoute,
  AuthenticatedHabitsAnalyticsRoute: AuthenticatedHabitsAnalyticsRoute,
  AuthenticatedHabitsDhikrRoute: AuthenticatedHabitsDhikrRoute,
  AuthenticatedHabitsLibraryRoute: AuthenticatedHabitsLibraryRoute,
  AuthenticatedHabitsIndexRoute: AuthenticatedHabitsIndexRoute,
}

const AuthenticatedHabitsRouteWithChildren =
  AuthenticatedHabitsRoute._addFileChildren(AuthenticatedHabitsRouteChildren)

interface AuthenticatedQuranRouteChildren {
  AuthenticatedQuranBookmarksRoute: typeof AuthenticatedQuranBookmarksRoute
  AuthenticatedQuranDuasRoute: typeof AuthenticatedQuranDuasRoute
  AuthenticatedQuranHadithRoute: typeof AuthenticatedQuranHadithRoute
  AuthenticatedQuranHifzRoute: typeof AuthenticatedQuranHifzRoute
  AuthenticatedQuranPracticeRoute: typeof AuthenticatedQuranPracticeRoute
  AuthenticatedQuranSearchRoute: typeof AuthenticatedQuranSearchRoute
  AuthenticatedQuranStatsRoute: typeof AuthenticatedQuranStatsRoute
  AuthenticatedQuranIndexRoute: typeof AuthenticatedQuranIndexRoute
  AuthenticatedQuranSurahIdRoute: typeof AuthenticatedQuranSurahIdRoute
}

const AuthenticatedQuranRouteChildren: AuthenticatedQuranRouteChildren = {
  AuthenticatedQuranBookmarksRoute: AuthenticatedQuranBookmarksRoute,
  AuthenticatedQuranDuasRoute: AuthenticatedQuranDuasRoute,
  AuthenticatedQuranHadithRoute: AuthenticatedQuranHadithRoute,
  AuthenticatedQuranHifzRoute: AuthenticatedQuranHifzRoute,
  AuthenticatedQuranPracticeRoute: AuthenticatedQuranPracticeRoute,
  AuthenticatedQuranSearchRoute: AuthenticatedQuranSearchRoute,
  AuthenticatedQuranStatsRoute: AuthenticatedQuranStatsRoute,
  AuthenticatedQuranIndexRoute: AuthenticatedQuranIndexRoute,
  AuthenticatedQuranSurahIdRoute: AuthenticatedQuranSurahIdRoute,
}

const AuthenticatedQuranRouteWithChildren =
  AuthenticatedQuranRoute._addFileChildren(AuthenticatedQuranRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedChildrenRoute: typeof AuthenticatedChildrenRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedFemaleRoute: typeof AuthenticatedFemaleRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGamificationRoute: typeof AuthenticatedGamificationRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRouteWithChildren
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedMealRoute: typeof AuthenticatedMealRoute
  AuthenticatedPrayerRoute: typeof AuthenticatedPrayerRoute
  AuthenticatedQiblaRoute: typeof AuthenticatedQiblaRoute
  AuthenticatedQuranRoute: typeof AuthenticatedQuranRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedWaqfRoute: typeof AuthenticatedWaqfRoute
  AuthenticatedWellnessRoute: typeof AuthenticatedWellnessRoute
  AuthenticatedWorkoutRoute: typeof AuthenticatedWorkoutRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedChildrenRoute: AuthenticatedChildrenRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedFemaleRoute: AuthenticatedFemaleRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGamificationRoute: AuthenticatedGamificationRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRouteWithChildren,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedMealRoute: AuthenticatedMealRoute,
  AuthenticatedPrayerRoute: AuthenticatedPrayerRoute,
  AuthenticatedQiblaRoute: AuthenticatedQiblaRoute,
  AuthenticatedQuranRoute: AuthenticatedQuranRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedWaqfRoute: AuthenticatedWaqfRoute,
  AuthenticatedWellnessRoute: AuthenticatedWellnessRoute,
  AuthenticatedWorkoutRoute: AuthenticatedWorkoutRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
